 Map<String, String> en = {
  "warehouse.noneType":"Không có loại phiếu",
  "warehouse.inventoryIn": "Kho nhận",
  "warehouse.inventoryOut": "Kho xuất",
  "warehouse.back": "quay lại",
  "warehouse.receiveProduct": "Nhận hàng",
  "warehouse.denyReceive": "Từ chối nhận",
  "warehouse.infoNote": "Thông tin phiếu",
  "warehouse.program": "Chương trình",
  "warehouse.typeNote": "Loại phiếu",
  "warehouse.type": "Loại",
  "warehouse.listProduct": "Danh sách sản phẩm",
  "warehouse.certifiesImage": "Hình ảnh chứng từ",
  "warehouse.note": "Ghi chú",
  "warehouse.typingNote": "Nhập ghi chú",
  "warehouse.next": "Tiếp theo",
  "warehouse.reason": "Lý do",
  "warehouse.equal": "Khớp",
  "warehouse.notEqual": "Lệch",
  "warehouse.quantity": "Số lượng",
  "warehouse.quantityActual": "Thực nhận",
  "warehouse.alertNumber": "Phải là số!",
  "warehouse.alertCamera": "Chỉ xem...",
  "warehouse.validateImage": "chưa có hình ảnh",
  "warehouse.validateReason": "chưa có ghi chú",
  "warehouse.validateQuantityActual": "chưa điền thực nhận",
  "warehouse.notifySendData": "Đang gửi dữ liệu",
  "warehouse.alertReason": "Lý do bắt buộc nhập",
  "warehouse.in": "Nhập",
  "warehouse.out": "mất/hư hỏng/nhận lệch",
  "warehouse.noData": "Không có dữ liệu",
  "warehouse.viewData": "Xem dữ liệu",
  "warehouse.import": "nhập",
  "warehouse.export": "mất/hư hỏng/nhận lệch",
  "warehouse.listData": "Danh sách dữ liệu",
  "warehouse.data": "Dữ liệu",
  "warehouse.time": "Thời gian",
  "warehouse.numericsOrder": "STT",
  "warehouse.name": "Tên",
  "warehouse.exist": "Tồn",
  "warehouse.saleNumber": "Số Bán",
  "warehouse.top10": "Top 10",
  "warehouse.warningGift": "Cảnh báo quà",
  "warehouse.dataChangeGift": "Dữ liệu đổi quà",
  "warehouse.detailData": "Dữ liệu chi tiết",
  "warehouse.compactQuantity": "S.L",
  "warehouse.money": "Tiền",
  "warehouse.outOfStock":"Hết hàng",
  "warehouse.needAdd": "Cần châm",
  "warehouse.safe": "An toàn",
  "warehouse.inventoryExist": "Tồn kho",
  "warehouse.listRequired": "Danh sách yêu cầu",
  "warehouse.listRequiredCompact": "D.s yêu cầu",
  "warehouse.filterData": "Lọc dữ liệu",
  "warehouse.requestRotation": "Yêu cầu luân chuyển",
  "warehouse.ticketRotation": "Phiếu luân chuyển",
  "warehouse.divided": "nhập",
  "warehouse.createTicket": "Tạo phiếu",
  "warehouse.ticket": "Phiếu",
  "warehouse.transferTicket": "Phiếu xuất",
  "warehouse.debitGift": "Báo nợ quà",
  "warehouse.debitGiftTicket": "Phiếu nợ quà",
  "warehouse.requestGift": "Yêu cầu quà",
  "warehouse.requestGiftTicket": "Phiếu yêu cầu quà",
  "warehouse.warning": "Cảnh báo",
  "warehouse.statusReport": "Tình trạng báo cáo",
  "warehouse.alertGetDetailData": "Đang lấy dữ liệu chi tiết",
  "warehouse.product": "Sản phẩm",
  "warehouse.quantityProduct": "Số SP",
  "warehouse.numberSale": "Số Sale",
  "warehouse.editProduct": "Sửa sản phẩm",
  "warehouse.edit": "Sửa",
  "warehouse.store": "Cửa hàng",
  "warehouse.noReport": "TT báo cáo",
  "warehouse.noConfirm": "TT xác nhận",
  "warehouse.oosReportConfirm": "Xác nhận báo cáo OOS",
  "warehouse.alert": "Thông báo",
  "warehouse.oosConfirmAlert": "Sau khi xác nhận dữ liệu sẽ bị khóa và không thể chỉnh sửa, vẫn tiếp tục?",
  "warehouse.confirm": "Xác nhận",
  "warehouse.approve": "Duyệt",
  "warehouse.noteDenyApprove": "Ghi chú từ chối duyệt",
  "warehouse.deny": "Từ chối",
  "warehouse.storeAddress": "Địa chỉ CH",
  "warehouse.quantityExport": "Số lượng xuất",
  "warehouse.compactProduct": "sp",
  "warehouse.customer": "Khách hàng",
  "warehouse.inventoryImport": "Kho nhập",
  "warehouse.quantityImport": "Số lượng nhập",
  "warehouse.position": "Vị trí",
  "warehouse.workDate": "Ngày làm việc",
  "warehouse.shift": "Ca",
  "warehouse.workplace": "Nơi làm việc",
  "warehouse.exportPlace": "Nơi xuất",
  "warehouse.importPlace": "Nơi nhận",
  "warehouse.noEmp": "Không có nhân viên",
  "warehouse.createrTicket": "Người tạo phiếu",
  "warehouse.handler": "Người xử lý",
  "warehouse.approver": "Người duyệt",
  "warehouse.alertNoneFunction": "Chức năng chưa thực hiện",
  "warehouse.dividedTicket": "Phiếu nhập",
  "warehouse.exportTicket": "Phiếu mất/hư hỏng/nhận lệch",
  "warehouse.addNewOutlet": "Thêm tủ mới",
  "warehouse.recallOutlet": "Thu hồi tủ",
  "warehouse.convertOutlet": "Chuyển đổi outlet",
  "warehouse.maintainOutlet": "Bảo trì tủ",
  "warehouse.inventoryImportTicket": "phiếu nhập",
  "warehouse.inventoryExportTicket": "phiếu xuất kho",
  "warehouse.detailRequestNewOutlet": "Chi tiết yêu cầu lắp tủ mới",
  "warehouse.detailRequestRecall": "Chi tiết yêu cầu thu hồi",
  "warehouse.detailRequestConvert": "Chi tiết yêu cầu chuyển đổi outlet",
  "warehouse.requestMaintain": "yêu cầu bảo trì",
  "warehouse.alertApproveRequest": "Loại yêu cầu không tồn tại!",
  "warehouse.status": "Trạng thái",
  "warehouse.infoCustomer": "Thông tin khách hàng",
  "warehouse.nameCustomer": "Họ tên khách hàng",
  "warehouse.phoneCustomer": "Số điện thoại khách hàng",
  "warehouse.addressCustomer": "Địa chỉ khách hàng",
  "warehouse.listGift": "Danh sách quà",
  "warehouse.list": "Danh sách",
  "warehouse.update": "Cập nhật",
  "warehouse.handle": "Xử lý",
  "warehouse.alertInitData": "Có lỗi xảy ra khi load dữ liệu",
  "warehouse.validateProgram": "Chưa chọn chương trình",
  "warehouse.validateStore": "Chưa chọn cửa hàng",
  "warehouse.validateReasonGift": "Chưa chọn lý do nợ quà",
  "warehouse.validateNameCustomer": "Tên khách hàng không được bỏ trống",
  "warehouse.validatePhoneCustomer":"Số điện thoại khách hàng không hợp lệ",
  "warehouse.validateAddressCustomer": "Địa chỉ khách hàng không được bỏ trống",
  "warehouse.validateListGift": "Danh sách quà không được bỏ trống",
  "warehouse.validateTypeRequest": "Chưa chọn loại yêu cầu",
  "warehouse.validateTypeTicket": "Chưa chọn loại phiếu",
  "warehouse.validateType": "Chưa chọn loại",
  "warehouse.validateInventory": "Chưa chọn kho",
  "warehouse.validateFromInv": "Chưa chọn từ kho",
  "warehouse.validateToInv": "Chưa chọn đến kho",
  "warehouse.validateEmployee": "Chưa chọn nhân viên",
  "warehouse.validateCertificatedImage": "Phải chụp ảnh chứng từ",
  "warehouse.validateDateWork": "Chưa chọn ngày làm việc",
  "warehouse.validateShiftWork": "Chưa chọn ca làm việc",
  "warehouse.validateFromShift": "Chưa chọn từ ca làm",
  "warehouse.validateToShift": "Chưa chọn đến ca làm",
  "warehouse.validateWorkPlace": "Chưa chọn nơi làm việc",
  "warehouse.validatePosition": "Chưa chọn vị trí",
  "warehouse.alertGetDataProgram": "Đang tải dữ liệu chương trình",
  "warehouse.alertGetDataStore": "Lấy dữ liệu cửa hàng",
  "warehouse.alertGetDataGift": "Lấy dữ liệu quà",
  "warehouse.alertHandleData": "Đang xử lý dữ liệu",
  "warehouse.alertTypeExport": "Lấy dữ liệu loại xuất",
  "warehouse.alertGetDateEmp": "Lấy dữ liệu nhân viên",
  "warehouse.alertGetDataShift": "Lấy dữ liệu ca làm việc",
  "warehouse.alertGetWorkplace": "Lấy dữ liệu nơi làm việc",
  "warehouse.alertGetRequestLocation": "Lấy dữ liệu vị trí yêu cầu",
  "warehouse.typeRequest": "Loại yêu cầu",
  "warehouse.create": "Tạo",
  "warehouse.inventory": "Kho",
  "warehouse.employee": "Nhân viên",
  "warehouse.confirmTicket": "Xác nhận phiếu",
  "warehouse.alertGetDataInventory": "Lấy dữ liệu kho",
  "warehouse.getData": "Lấy dữ liệu",
  "warehouse.alertConfirmBill" :"Sau khi xác nhận thì không thể chỉnh sửa số lượng",
  "warehouse.getDataTicket": "Đang lấy thông tin phiếu",
  "warehouse.alertValidLink": "Đường dẫn không tồn tại!",
  "warehouse.fromInventory": "Từ kho",
  "warehouse.alertDupInventory": "Kho chuyển và kho nhận không được trùng",
  "warehouse.toInventory":"Đến kho",
  "warehouse.allInventory": "tất cả kho",
  "warehouse.myInventory": "kho của tôi",
  "warehouse.validateFromStore": "Không thể xuất và nhận cùng một kho",
  "warehouse.timeWork": "Ca làm việc",
  "warehouse.toDate": "Đến ngày",
  "warehouse.from": "Từ",
  "warehouse.to": "Đến",
  "warehouse.alertDupTime": "Từ giờ và đến giờ không được trùng",
  "warehouse.sendRequest": "Gửi yêu cầu",
  "warehouse.existInvSKU": "Tồn kho SKU",
  "warehouse.detail": "Chi tiết",
  "warehouse.view": "Xem",
  "warehouse.viewTicket": "Xem phiếu",
  "warehouse.inventoryHome.tableOut": "Xuất",
  "warehouse.inventoryHome.existTable": "Tồn",
  "warehouse.inventoryHome.inTable": "Nhập",
  "warehouse.inventoryHome.saleNumber": "Số Bán",
  "warehouse.createWHInOut.rejectBill": "Từ chối nhận",
  "warehouse.createWHInOut.rejectBillAlert": "Bạn chắc chắn muốn từ chối nhận hàng không?",
  "warehouse.createWHInOut.rejectBillReason": "Hãy nhập lí do từ chối nhận hàng",
  "warehouse.createWHInOut.rejectBillValidateReason": "Chưa nhập lí do từ chối nhân",
  "warehouse.productHandle.quantityCreated": "Số lượng chuyển",
  "warehouse.productHandle.quantity": "Số lượng",
};