// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBktUU2daQemPb5Udq9Z_PY4H68ij0RGPU',
    appId: '1:985024137205:android:46b1cec3f61f2bdfbf82bc',
    messagingSenderId: '985024137205',
    projectId: 'acacy-prol',
    storageBucket: 'acacy-prol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA1MFMAotZm0WU-JG2JSWsRg7oG-wgvhY',
    appId: '1:985024137205:ios:23acff71a5117e52bf82bc',
    messagingSenderId: '985024137205',
    projectId: 'acacy-prol',
    storageBucket: 'acacy-prol.appspot.com',
    androidClientId: '985024137205-10pr50jttgqu7e1je47qfpfchlf3i0m4.apps.googleusercontent.com',
    iosClientId: '985024137205-gqokfpk44735l3vs8671vj8t3fpmq28m.apps.googleusercontent.com',
    iosBundleId: 'com.acacy.erp',
  );
}
