name: erpcore
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  package_info: ^2.0.2
  connectivity: ^3.0.6
  device_info: ^2.0.3
  dio: ^4.0.6
  fluttertoast: ^8.0.8
  uuid: ^3.0.5 # tạo sysCode
  path: ^1.8.0
  path_provider: ^2.0.14
  carousel_slider: ^4.2.1
  intl: ^0.17.0
  flutter_slidable: ^3.1.0
  date_format: ^2.0.7
  geolocator: ^9.0.2
  flutter_fortune_wheel: ^1.2.1 ## vòng quay may mắn
  confetti: ^0.7.0 # tạo hiệu ứng chúc mừng khi trúng thưởng
  image_picker: ^0.8.7
  url_launcher: ^6.1.6
  get: ^4.6.5
  photo_view: ^0.14.0
  record: ^4.4.4
  shimmer: ^2.0.0
  flutter_speed_dial: ^6.2.0
  flutter_datetime_picker_bdaya: ^3.0.1
  google_fonts: ^4.0.3
  charts_flutter: ^0.12.0
  #signalr_netcore: ^1.3.3
  #ota_update: ^6.0.0
  # camera: ^0.10.5+2
  # firebase_messaging: 14.5.0
  # firebase_core: 2.11.0
  flutter_local_notifications: ^13.0.0
  file_picker: ^5.2.5
  flutter_spinkit: ^5.1.0
  local_auth: ^2.1.2
  im_stepper: ^1.0.1+1
  firebase_performance: 0.9.0+15
  diacritic: ^0.1.3
  flutter_app_badger: ^1.5.0
  flutter_email_sender: ^5.1.0
  archive: ^3.4.10
  get_storage: ^2.0.3
  flutter_js: ^0.8.0
  flutter_image_compress: ^1.1.3
  perfect_volume_control: ^1.0.5
  workmanager: ^0.5.2
  firebase_crashlytics: 3.2.0
  shared_preferences: ^2.1.0
  image: ^4.0.16
  wakelock: ^0.4.0
  share_plus: 7.2.1
  image_gallery_saver: ^1.7.1
  datetime_setting: ^2.0.2
  flutter_jailbreak_detection: ^1.10.0
  flutter_native_timezone: ^2.0.0
  loading_animation_widget: ^1.2.0+4
  flutter_svg: ^2.0.7
  flutter_pdfview: ^1.3.2
  rive: ^0.11.4
  mobile_scanner: 3.5.5
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_text_recognition: ^0.11.0
  uni_links: ^0.5.1
  sembast: ^3.5.0+1
  flutter_reorderable_grid_view: ^4.0.0
  pdf: ^3.10.7
  file_saver: 0.2.9
  flutter_switch: ^0.3.2
  cron: ^0.5.1
  cached_network_image: ^3.3.0
  camera: ^0.10.5+7
  permission_handler: ^11.1.0
  audioplayers: ^5.2.1
  pdf_render: ^1.4.0
  flutter_inappwebview: 6.0.0
  flutter_widget_from_html: ^0.14.11
  fl_chart: ^0.66.2
  upgrader: ^9.0.0
  firebase_messaging: ^14.6.9
  firebase_core: ^2.17.0
  signalr_netcore: ^1.3.7
  app_links: ^3.5.0
  shorebird_code_push: ^1.1.3
  encrypt: ^5.0.3
dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
dependency_overrides:
  firebase_core_platform_interface: 5.0.0
  encrypt: ^5.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
